arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - Joint_1
    - Joint_2
    - Joint_3
    - Joint_4
    - Joint_5
    - gripper
  gains:
    Joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    gripper:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Joint_1
    - Joint_2
    - Joint_3
    - Joint_4
    - Joint_5
    - gripper
  gains:
    Joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    gripper:
      p: 100
      d: 1
      i: 1
      i_clamp: 1